Getting Started in OpenCV
===

## Reading an Image

We use the function `cv2.imread()` to read an image.

In [23]:
import cv2
import numpy as np

In [35]:
# first argument is the image to load
# second argument is the color of the image
    # cv2.IMREAD_COLOR loads a color image
    # cv2.IMREAD_GRAYSCALE loads image in grayscale
#image = cv2.imread('image02.jpg', cv2.IMREAD_COLOR)
image = cv2.imread('image02.jpg', 1)
print(type(image))
img = cv2.imread('image02.jpg', 0)
print(image)
img.shape
image.shape

<class 'numpy.ndarray'>
[[[141 158 167]
  [142 159 168]
  [142 159 168]
  ...
  [ 13  23  41]
  [ 13  21  44]
  [ 13  21  44]]

 [[142 159 168]
  [143 160 169]
  [143 160 169]
  ...
  [ 21  31  49]
  [ 14  22  45]
  [ 14  22  45]]

 [[144 161 170]
  [144 161 170]
  [145 162 171]
  ...
  [ 12  22  40]
  [ 15  23  46]
  [ 15  23  46]]

 ...

 [[133 142 151]
  [131 140 149]
  [129 138 147]
  ...
  [146 145 141]
  [142 141 137]
  [142 141 137]]

 [[138 147 156]
  [136 145 154]
  [135 144 153]
  ...
  [111 110 106]
  [132 131 127]
  [132 131 127]]

 [[142 151 160]
  [141 150 159]
  [140 149 158]
  ...
  [140 139 135]
  [136 135 131]
  [136 135 131]]]


(366, 650, 3)

## Displaying an Image

We use the function `cv2.imshow()` to display an image.

In [36]:
cv2.imshow('image', img)
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

`cv2.waitKey()` is a keyboard binding function, which means it waits for a specified amount of time (in milliseconds) for any keyboard event. If any key was pressed within the time, the program continues. If `0` is passed, it waits indefinitely.

`cv2.destroyAllWindows()` destroys all windows created. To destroy a specific window, use `cv2.destroyWindow()` with the window name passed as an argument.

In [29]:
cv2.namedWindow('image', cv2.WINDOW_NORMAL)
cv2.imshow('image', image)
cv2.waitKey(0)
cv2.destroyWindow('image')

`cv2.namedWindow()` creates a window where an image may be loaded. The window may be specified to be resizable or not. The default flag is `cv2.WINDOW_AUTOSIZE`. Meanwhile, if you specify the flag as `cv2.WINDOW_NORMAL`, the window may be resizable.

In [45]:
# Black and White (gray scale)
 
img = cv2.imread('image02.jpg',0)
 
resized_image = cv2.resize(img, (300,300))
 
cv2.imshow('image_greyscale', resized_image)
 
cv2.waitKey(0)
 
cv2.destroyAllWindows()

In [44]:
#Resized_image = cv2.resize(img, int(img.shape[1]/2), int(img.shape[0]/2))


## Writing an Image

We use the function `cv2.imwrite()` to save an image.

First argument is the file name, while the second is the image to be saved.

In [18]:
image = cv2.imread('image02.jpg', cv2.IMREAD_GRAYSCALE)
cv2.imwrite('image02_grayscale.jpg', image)

True

## Summary

Let us load our image in grayscale, display it, then save it.

In [19]:
image = cv2.imread('image02.jpg', cv2.IMREAD_GRAYSCALE)
cv2.imshow('image', image)

k = cv2.waitKey(0)

if k == 27:    # wait for ESC to exit
    cv2.destroyAllWindows()
elif k == ord('s'):    # wait for 's' key to save and exit
    cv2.imwrite('image02.jpg', image)
    cv2.destroyAllWindows()

## Video in OpenCV

### Capture Video from Camera

To capture a video, we need to create a `cv2.VideoCapture` object. The argument for this may be the device index or the name of a video file.

In [1]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)
n=0
while n<500:                  #capture video for 500 milliseconds
    
    _, frame = cap.read()
    
    cv2.imshow('webcam', frame)
    
    if cv2.waitKey(1) == 5:
        break
    n=n+1
        
cap.release()
cv2.destroyAllWindows()